### ISSUE TITLE
Hey.. 

### ISSUE THREAD

**Issue by joshbelmar** [dospunk/dospunk.github.io#1]
So, this is probably shitty of me, but i wasnt sure how else to get ahold of ya . Im doing something with TinyTag and i seen you have some experience. Audacity's meta tag stuff, extra bits at the end of the file ? Did you ever find a working solution to read it ? Thanks. joshbelmar@gmail.com

**Comment by dospunk** [comment]
Hey, sorry I just now noticed this. The only way I found to deal with the extra bits was to manually delete them
